- name: Install Redis Repos
  yum:
   name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
   state: present
   
- name: Install Redis
  yum: 
   name: redis
   enablerepo: remi
   state: present

- name: Update Redis Listen Address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Redis Service
  systemd: 
    name: redis
    enabled: yes
    state: started





#Manual Installation of Redis.
#Install Redis.
# yum install epel-release yum-utils -y
# yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y
# yum-config-manager --enable remi
# yum install redis -y
#Update the BindIP from 127.0.0.1 to 0.0.0.0 in config file /etc/redis.conf & /etc/redis/redis.conf

#Start Redis Database

# systemctl enable redis
# systemctl start redis