- name: Demo on Vairables
  hosts: all
  vars:
   URL1: play.google.com   # play level vairable
   URL: play.google.com
  vars_files:
    - vars.yaml
  tasks:
    - name: Print a Vairable from file
      debug:
        msg: URL = {{URL1}}
    - name: Print a variable from file
      debug:
         msg: URL = {{URL2}}
    - name: Demo on Task level vairables
      vars:
       URL3: tasks.google.com
      debug:
        msg: URL = {{URL3}}
    - name: Print variable from host file
      debug: 
        msg: URL = {{URL4}}
    - name: Print Variable from CLI
      debug:
        msg: URL = {{URL5}}
    - name: Show variable precendence
      vars:
        URL: tasks.google.com
      debug:
       msg: URL = {{URL}}