- name: Demo on Conditions
  hosts: localhost
  tasks:
    - name: CentOS
      debug:
       msg: CentOS
      when: OS == "centos"
    - name:
      debug:
       msg: Ubuntu
      when: OS == "ubuntu"
       
    