- name: Demo on Conditions
  hosts: localhost
  vars:
    OS: centos
    NUM: 7
    BOOL1 : false
  tasks:
    - name: CentOS
      debug:
       msg: CentOS
      when: OS == "centos"
    - name: Ubuntu
      debug:
       msg: Ubuntu
      when: OS == "ubuntu"
    - name: NUM Condition - 1
      debug:
       msg: NUM Con 1
      when: NUM > 5
    - name: NUM Condition - 2
      debug:
       msg: NUM Con 1
      when: NUM <= 5
      
    - name: if Bool1 is true
      debug:
        msg: bool 1 is true
      when: BOOL1 | bool
      
      
    - name: Multipile statements ,OR
      debug:
       msg: either or statements
      when: NUM >= 5 or BOOL1 | bool
       
    
    - name: Multipile statements ,AND
      debug:
       msg: AND Statement
      when: NUM >= 5 and BOOL1 | bool
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      # Difference between number and string is, strings are quoted and numbers are not .
      # Here vairable would be starting value and it should not bbe quoted.
      # Latest version of ansible suggest ed using boolean with " |bool"
      