- name: loops
  hosts: localhost
  tasks:
   - name: print
     debug:
        msg: Hello, {{item}}
     loop:
        - John
        - Ram
   - name: Print Loop from the map
     debug: 
        msg: Hello {{item.name}} course is {{item.course}}
     loop:
       - { name: John , course: aws }
       - { name: Ram ,  course: DevOps }