- name: Roboshop Project Setup - FRONTEND
  hosts: FRONTEND
  tags: frontend
  become: yes
  roles:
    - frontend

- name: Roboshop Project Setup - MongoDB
  hosts: MONGODB
  tags: mongodb
  become: yes
  roles:
    - mongodb
    
- name: Roboshop Project Setup - Catalouge
  hosts: CATALOGUE
  tags: catalogue
  become: yes
  roles:
    - catalogue
    
- name: Roboshop Project Setup - redis
  hosts: REDIS
  tags: redis
  become: yes
  roles:
    - redis
    
    
- name: Roboshop Project Setup - User
  hosts: USER
  tags: user
  become: yes
  roles:
    - user
    
- name: Roboshop Project Setup - Cart
  hosts: CART
  tags: CART
  become: yes
  roles:
    - cart
    
- name: Roboshop Project Setup - MySQL
  hosts: MYSQL
  tags: mysql
  become: yes
  roles:
    - mysql
    
- name: Roboshop Project Setup - Shipping
  hosts: SHIPPING
  tags: shipping
  become: yes
  roles:
    - shipping
    
- name: Roboshop Project Setup - RabbitMQ
  hosts: RABBITMQ
  tags: rabbitmq
  become: yes
  roles:
    - rabbitmq
    
- name: Roboshop Project Setup - Payment
  hosts: PAYMENT
  tags: payment
  become: yes
  roles:
    - payment
